---
- name: Check if squirrel is installed, only install software if existing version does not match
  command: ls /home/vagrant/installed_software/{{app}}-{{version}}.txt
  register: squirrelsql_check
  ignore_errors: yes

- name: Download SQuirreL
  get_url: url={{url}} dest={{temp_install_path}}/{{filename}}
  when: squirrelsql_check.rc != 0

- name: Unarchive SQuirreL
  unarchive: src={{temp_install_path}}/{{filename}} dest={{temp_install_path}} copy=no
  
- name: Clean up any SQuirreL
  file: state=absent path={{install_dir}}
  when: squirrelsql_check.rc != 0

- name: Move directory
  command: "mv {{temp_install_path}}/{{temp_install_dir}} {{install_dir}}"  
  when: squirrelsql_check.rc != 0

- name: Fix ownership
  file: state=directory path={{install_dir}} owner=root group=root recurse=yes
  when: squirrelsql_check.rc != 0

- name: Clean up
  file: state=absent path={{temp_install_path}}/{{filename}}
  when: squirrelsql_check.rc != 0

- name: Make the Shell Script that invokes SQuirrel have execute permissions
  file: path={{install_dir}}/{{executable}} owner=root group=root mode=o+wrx
  when: squirrelsql_check.rc != 0

- name: Create shell script content to /usr/bin
  shell: printf '#!/bin/bash\n{{install_dir}}/{{executable}}' > /usr/bin/{{executable}}
  args:
    executable: /bin/bash
  when: squirrelsql_check.rc != 0
  
- name: Create desktop link for SQuirreL
  copy: src=/home/vagrant/share/files/{{app}}/{{app}}.desktop dest=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant
  when: squirrelsql_check.rc != 0

- name: Permissions for desktop link for SQuirreL
  file: path=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant mode="u+x,g+x,o+x"
  when: squirrelsql_check.rc != 0

- name: Set squirrel as installed software
  shell: echo > /home/vagrant/installed_software/{{app}}-{{version}}.txt
  args:
    executable: /bin/bash
  when: squirrelsql_check.rc != 0