---
- name: Check if node is installed, only install software if existing version does not match
  command: ls /home/vagrant/installed_software/{{app}}-{{version}}.txt
  register: node_check
  ignore_errors: yes

- name: Clean up any node
  file: state=absent path={{temp_install_path}}/{{temp_install_dir}}
  when: node_check.rc != 0
  
- name: Download Node
  unarchive: src={{url}} dest={{temp_install_path}} copy=no
  when: node_check.rc != 0

- name: Move directory
  command: "mv {{temp_install_path}}/{{temp_install_dir}} {{install_dir}}"  
  when: node_check.rc != 0
  
- name: Setup Node and NPM in Path Env variable
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{path_dir}}).*?)(["]*)$'
    line="PATH=\1\2:{{path_dir}}\3"
  when: node_check.rc != 0

- name: Set node as installed software
  shell: echo > /home/vagrant/installed_software/{{app}}-{{version}}.txt
  args:
    executable: /bin/bash
  when: node_check.rc != 0