---
- name: Check if eclipse is installed, only install software if existing version does not match
  command: ls /home/vagrant/installed_software/{{app}}-{{version}}.txt
  register: eclipse_check
  ignore_errors: yes

- name: Clean up any Eclipse
  file: state=absent path={{install_dir}}
  when: eclipse_check.rc != 0

- name: Download Eclipse
  unarchive: src={{url}} dest={{temp_install_dir}} copy=no
  when: eclipse_check.rc != 0

- name: Move directory
  command: "mv {{temp_install_dir}}/{{app}} {{install_dir}}"  
  when: eclipse_check.rc != 0

- name: Create symbolic link add to /usr/bin
  file: src={{install_dir}}/{{executable}} dest=/usr/bin/{{executable}} owner=root group=root state=link
  when: eclipse_check.rc != 0

- name: Create desktop link for Eclipse
  copy: src=/home/vagrant/share/files/{{app}}/{{app}}.desktop dest=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant
  when: eclipse_check.rc != 0

- name: Permissions for desktop link for Eclipse
  file: path=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant mode="u+x,g+x,o+x"
  when: eclipse_check.rc != 0

- name: Set eclipse as installed software
  shell: echo > /home/vagrant/installed_software/{{app}}-{{version}}.txt
  args:
    executable: /bin/bash
  when: eclipse_check.rc != 0