---
# Source: https://github.com/sheldonh/dotfiles-ansible/blob/master/
## OS SPECIFIC: change this for different distro
- name: Enable Yum repo for Google Chrome
  copy: src=/home/vagrant/share/files/{{app}}/google-chrome.repo dest=/etc/yum.repos.d/google-chrome.repo

- name: Install Google Chrome
  yum: name=google-chrome-stable state=present
## END OS SPECIFIC

- name: Create desktop link for Chrome
  copy: src=/home/vagrant/share/files/{{app}}/{{app}}.desktop dest=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant

- name: Permissions for desktop link for Chrome
  file: path=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant mode="u+x,g+x,o+x"